CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50) NOT NULL
);

CREATE TABLE "roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50) NOT NULL
);

CREATE TABLE "courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "category" int NOT NULL,
  "title" int NOT NULL,
  "descritpion" varchar(200) NOT NULL,
  "level" varchar(15) NOT NULL,
  "teacher" int NOT NULL
);

CREATE TABLE "courses_video" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "course" int NOT NULL,
  "title" varchar(50) NOT NULL,
  "url" varchar(100) NOT NULL
);

CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "rol" int NOT NULL,
  "name" varchar(50) NOT NULL,
  "email" varchar(50) NOT NULL,
  "password" varchar(15) NOT NULL,
  "age" int NOT NULL
);

CREATE TABLE "users_courses" (
  "id_user" int NOT NULL,
  "id_course" int NOT NULL
);

CREATE TABLE "teachers" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50) NOT NULL
);

ALTER TABLE "users" ADD FOREIGN KEY ("rol") REFERENCES "roles" ("id");

ALTER TABLE "users_courses" ADD FOREIGN KEY ("id_user") REFERENCES "users" ("id");

ALTER TABLE "users_courses" ADD FOREIGN KEY ("id_course") REFERENCES "courses" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("category") REFERENCES "categories" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("title") REFERENCES "courses_video" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("teacher") REFERENCES "teachers" ("id");




-- INDICACIONES SQL SHELL

INSERT INTO teachers (name) VALUES ('Brenda'), ('Andrés');

INSERT INTO courses_video (course, title, url) VALUES (1, 'Javascript', 'www.javascript.com'), (2, 'React', 'www.react.com');

INSERT INTO categories (name) VALUES ('Fundamentos'), ('Aplicaciones');

INSERT INTO roles (name) VALUES ('Student'), ('Teacher');

INSERT INTO users (rol, name, email, password, age) VALUES (1, 'Aldo', 'aldo@gmail.com', '1234', 26), (2, 'Jesús', 'jesus@gmail.com', '5678', 30);

INSERT INTO courses (category, title, descritpion, level, teacher) VALUES (1, 1, 'Clase de fundamentos', 'principiante', 1), (2, 2, 'Creación de aplicaciones', 'medio', 2);

INSERT INTO users_courses (id_user, id_course) VALUES (1, 1), (2, 1);

SELECT * FROM users_courses JOIN courses ON courses.id=users_courses.id_course;



